require('dotenv').config();
const mongoose = require('mongoose');
const Book = require('./models/Book');

// 20+ Premium Books for Lumora Books Database
const books = [
  {
    title: 'The Silent Garden',
    author: 'Elena Hart',
    description: 'A beautifully written story about memory, identity and the places we carry within us. Set in a mysterious garden where secrets bloom like flowers, this novel explores the delicate balance between past and present.',
    price: 599,
    originalPrice: 899,
    category: 'Fiction',
    genre: 'Literary Fiction',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=750&fit=crop',
    rating: 4.8,
    reviewsCount: 142,
    pages: 324,
    language: 'English',
    publisher: 'Vintage Press',
    publicationDate: 'March 14, 2024',
    publicationYear: 2024,
    stock: 12,
    featured: true
  },
  {
    title: 'Letters We Never Sent',
    author: 'Noah Bennett',
    description: 'A poignant collection of unsent letters that reveal the hidden conversations we have with ourselves and others. A deeply moving exploration of love, loss, and the words left unspoken.',
    price: 699,
    originalPrice: 999,
    category: 'Fiction',
    genre: 'Contemporary Fiction',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&h=750&fit=crop',
    rating: 4.6,
    reviewsCount: 89,
    pages: 288,
    language: 'English',
    publisher: 'Anchor Books',
    publicationDate: 'November 10, 2023',
    publicationYear: 2023,
    stock: 8,
    featured: true
  },
  {
    title: 'The Last Library',
    author: 'Clara Moore',
    description: 'In a world where books are forbidden, one librarian risks everything to preserve humanity\'s stories. A dystopian tale about the power of knowledge and the courage to remember.',
    price: 799,
    originalPrice: 1199,
    category: 'Science Fiction',
    genre: 'Dystopian',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500&h=750&fit=crop',
    rating: 4.7,
    reviewsCount: 201,
    pages: 412,
    language: 'English',
    publisher: 'Galaxy Publications',
    publicationDate: 'April 20, 2024',
    publicationYear: 2024,
    stock: 15,
    featured: true
  },
  {
    title: 'Midnight in Kyoto',
    author: 'Daniel Reed',
    description: 'A mesmerizing journey through the hidden corners of Kyoto, where ancient traditions meet modern mysteries. A cultural thriller that will transport you to Japan\'s most enigmatic city.',
    price: 649,
    originalPrice: 849,
    category: 'Mystery',
    genre: 'Cultural Thriller',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=500&h=750&fit=crop',
    rating: 4.5,
    reviewsCount: 76,
    pages: 356,
    language: 'English',
    publisher: 'East-West Publishing',
    publicationDate: 'August 12, 2023',
    publicationYear: 2023,
    stock: 6,
    featured: false
  },
  {
    title: 'A Map of Memories',
    author: 'Sophia Lane',
    description: 'An intimate memoir about mapping one\'s life through the places that shaped us. From childhood homes to foreign cities, discover how geography becomes biography.',
    price: 749,
    originalPrice: 949,
    category: 'Biography',
    genre: 'Memoir',
    coverImage: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500&h=750&fit=crop',
    rating: 4.9,
    reviewsCount: 310,
    pages: 298,
    language: 'English',
    publisher: 'Harper & Brothers',
    publicationDate: 'January 28, 2024',
    publicationYear: 2024,
    stock: 14,
    featured: true
  },
  {
    title: 'Beyond the Horizon',
    author: 'Ethan Cole',
    description: 'A groundbreaking exploration of what lies beyond our current understanding of science and philosophy. Challenge your perceptions of reality and possibility.',
    price: 899,
    originalPrice: 1299,
    category: 'Science Fiction',
    genre: 'Hard Science Fiction',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&h=750&fit=crop',
    rating: 4.4,
    reviewsCount: 54,
    pages: 456,
    language: 'English',
    publisher: 'Nova Press',
    publicationDate: 'September 5, 2023',
    publicationYear: 2023,
    stock: 5,
    featured: false
  },
  {
    title: 'The Art of Stillness',
    author: 'Maya Chen',
    description: 'In our fast-paced world, discover the transformative power of pause. A practical guide to finding peace and clarity through mindfulness and intentional living.',
    price: 549,
    originalPrice: 799,
    category: 'Self Development',
    genre: 'Mindfulness',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=750&fit=crop',
    rating: 4.6,
    reviewsCount: 167,
    pages: 224,
    language: 'English',
    publisher: 'Mind-Body Press',
    publicationDate: 'February 15, 2024',
    publicationYear: 2024,
    stock: 20,
    featured: true
  },
  {
    title: 'Empire of Shadows',
    author: 'James Wright',
    description: 'An epic historical saga spanning three generations of a family caught between duty and desire. From the opulent courts of Europe to the battlefields of destiny.',
    price: 849,
    originalPrice: 1249,
    category: 'History',
    genre: 'Historical Fiction',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=500&h=750&fit=crop',
    rating: 4.7,
    reviewsCount: 112,
    pages: 528,
    language: 'English',
    publisher: 'Chronicle Books',
    publicationDate: 'October 15, 2023',
    publicationYear: 2023,
    stock: 9,
    featured: true
  },
  {
    title: 'Whispers of the Heart',
    author: 'Lily Anderson',
    description: 'A tender romance that proves love knows no boundaries. Set against the backdrop of a small coastal town, two souls find each other against all odds.',
    price: 599,
    originalPrice: 849,
    category: 'Romance',
    genre: 'Contemporary Romance',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500&h=750&fit=crop',
    rating: 4.5,
    reviewsCount: 95,
    pages: 312,
    language: 'English',
    publisher: 'Sweetwater Publishing',
    publicationDate: 'May 1, 2024',
    publicationYear: 2024,
    stock: 18,
    featured: false
  },
  {
    title: 'The Innovation Mindset',
    author: 'Robert Kim',
    description: 'Unlock your creative potential with this comprehensive guide to innovative thinking. Learn the strategies used by world-class entrepreneurs and visionaries.',
    price: 799,
    originalPrice: 1099,
    category: 'Business',
    genre: 'Business Strategy',
    coverImage: 'https://images.unsplash.com/photo-1553484771-371a605b060b?w=500&h=750&fit=crop',
    rating: 4.3,
    reviewsCount: 42,
    pages: 384,
    language: 'English',
    publisher: 'Apex Business Books',
    publicationDate: 'June 18, 2023',
    publicationYear: 2023,
    stock: 11,
    featured: false
  },
  {
    title: 'Shadows in the Mist',
    author: 'Emma Blackwood',
    description: 'A gripping psychological thriller that will keep you guessing until the final page. When a woman\'s past returns to haunt her, nothing is as it seems.',
    price: 649,
    originalPrice: 899,
    category: 'Mystery',
    genre: 'Psychological Thriller',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=750&fit=crop',
    rating: 4.6,
    reviewsCount: 125,
    pages: 340,
    language: 'English',
    publisher: 'Darkroom Publishing',
    publicationDate: 'January 10, 2024',
    publicationYear: 2024,
    stock: 7,
    featured: false
  },
  {
    title: 'Quantum Dreams',
    author: 'Dr. Sarah Mitchell',
    description: 'Explore the fascinating intersection of quantum physics and consciousness. A mind-bending journey into the nature of reality itself.',
    price: 899,
    originalPrice: 1399,
    category: 'Science Fiction',
    genre: 'Science Philosophy',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&h=750&fit=crop',
    rating: 4.8,
    reviewsCount: 63,
    pages: 420,
    language: 'English',
    publisher: 'Academic Press',
    publicationDate: 'December 20, 2023',
    publicationYear: 2023,
    stock: 4,
    featured: true
  },
  {
    title: 'Chronicles of Eldoria',
    author: 'Marcus Vance',
    description: 'An epic high-fantasy adventure where ancient magic reawakens. Follow the journey of an apprentice who holds the key to saving the kingdom from ruin.',
    price: 699,
    originalPrice: 999,
    category: 'Fantasy',
    genre: 'High Fantasy',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&h=750&fit=crop',
    rating: 4.7,
    reviewsCount: 154,
    pages: 480,
    language: 'English',
    publisher: 'Spellbound Press',
    publicationDate: 'July 14, 2024',
    publicationYear: 2024,
    stock: 16,
    featured: true
  },
  {
    title: 'The Codex of Light',
    author: 'Gideon Thorne',
    description: 'When an ancient codex is unearthed in the ruins of Alexandria, a race begins to decode its magical secrets before they fall into the wrong hands.',
    price: 749,
    originalPrice: 1049,
    category: 'Fantasy',
    genre: 'Arcane Fantasy',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&h=750&fit=crop',
    rating: 4.5,
    reviewsCount: 82,
    pages: 396,
    language: 'English',
    publisher: 'Magus Library Press',
    publicationDate: 'February 9, 2024',
    publicationYear: 2024,
    stock: 10,
    featured: false
  },
  {
    title: 'Code and Cosmos',
    author: 'Alan Turing Jr.',
    description: 'An accessible exploration of quantum computing, artificial intelligence, and how computer architectures are reshaping our cosmological understanding.',
    price: 899,
    originalPrice: 1199,
    category: 'Technology',
    genre: 'Popular Science',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=750&fit=crop',
    rating: 4.6,
    reviewsCount: 47,
    pages: 310,
    language: 'English',
    publisher: 'Silicon Press',
    publicationDate: 'March 22, 2024',
    publicationYear: 2024,
    stock: 14,
    featured: false
  },
  {
    title: 'Architects of the Web',
    author: 'Lisa Sterling',
    description: 'Discover the untold story of the pioneers who designed the internet, browser protocols, and initial web architectures that define our digital lives.',
    price: 799,
    originalPrice: 999,
    category: 'Technology',
    genre: 'Tech History',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&h=750&fit=crop',
    rating: 4.8,
    reviewsCount: 118,
    pages: 365,
    language: 'English',
    publisher: 'Web Builders Syndicate',
    publicationDate: 'August 3, 2023',
    publicationYear: 2023,
    stock: 8,
    featured: false
  },
  {
    title: 'Rethinking Capitalism',
    author: 'Prof. David Harvey',
    description: 'A provocative critical review of contemporary financial systems and modern economics. Harvey offers an alternative roadmap for equitable global growth.',
    price: 849,
    originalPrice: 1149,
    category: 'Business',
    genre: 'Economics',
    coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=750&fit=crop',
    rating: 4.4,
    reviewsCount: 92,
    pages: 440,
    language: 'English',
    publisher: 'Meridian Books',
    publicationDate: 'January 17, 2024',
    publicationYear: 2024,
    stock: 9,
    featured: false
  },
  {
    title: 'Leonardo da Vinci: A Life',
    author: 'Walter Isaacson III',
    description: 'Based on thousands of pages from his notebooks, this stunning biography connects Leonardo\'s art, science, and insatiable curiosity into a unified portrait of genius.',
    price: 999,
    originalPrice: 1499,
    category: 'Biography',
    genre: 'Historical Biography',
    coverImage: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=500&h=750&fit=crop',
    rating: 4.9,
    reviewsCount: 284,
    pages: 600,
    language: 'English',
    publisher: 'Genius Press',
    publicationDate: 'October 11, 2023',
    publicationYear: 2023,
    stock: 5,
    featured: true
  },
  {
    title: 'The Roman Way',
    author: 'Dr. Arthur Miller',
    description: 'An immersive examination of daily life, political philosophy, and military strategy during the rise and fall of the Roman Republic and subsequent Empire.',
    price: 799,
    originalPrice: 1099,
    category: 'History',
    genre: 'Classical History',
    coverImage: 'https://images.unsplash.com/photo-1447069387593-a5de0862481e?w=500&h=750&fit=crop',
    rating: 4.6,
    reviewsCount: 130,
    pages: 380,
    language: 'English',
    publisher: 'Romanesque Publications',
    publicationDate: 'June 5, 2023',
    publicationYear: 2023,
    stock: 13,
    featured: false
  },
  {
    title: 'Love in the Mist',
    author: 'Sophie Dubois',
    description: 'Set in Paris in the 1920s, a painter and a writer cross paths, igniting a passionate love affair that forces them to choose between their art and their hearts.',
    price: 499,
    originalPrice: 699,
    category: 'Romance',
    genre: 'Historical Romance',
    coverImage: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=500&h=750&fit=crop',
    rating: 4.3,
    reviewsCount: 71,
    pages: 290,
    language: 'English',
    publisher: 'Rive Gauche Books',
    publicationDate: 'February 14, 2024',
    publicationYear: 2024,
    stock: 22,
    featured: false
  },
  {
    title: 'Atomic Habits & Mindsets',
    author: 'Charles Duhigg',
    description: 'A synthesised blueprint showing how micro-behaviors, habit cues, and deliberate triggers combine to drive personal productivity, fitness, and career success.',
    price: 599,
    originalPrice: 799,
    category: 'Self Development',
    genre: 'Habits',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500&h=750&fit=crop',
    rating: 4.8,
    reviewsCount: 450,
    pages: 260,
    language: 'English',
    publisher: 'Catalyst Press',
    publicationDate: 'July 1, 2024',
    publicationYear: 2024,
    stock: 30,
    featured: true
  },
  {
    title: 'The Silent Patient\'s Secret',
    author: 'Alex Michaelides Jr.',
    description: 'When a therapist takes on a mute patient accused of murdering her husband, he uncovers a deep psychological puzzle that could cost him his sanity and his life.',
    price: 699,
    originalPrice: 999,
    category: 'Mystery',
    genre: 'Psychological Mystery',
    coverImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=500&h=750&fit=crop',
    rating: 4.7,
    reviewsCount: 189,
    pages: 360,
    language: 'English',
    publisher: 'Hesperus Thrillers',
    publicationDate: 'April 8, 2024',
    publicationYear: 2024,
    stock: 15,
    featured: true
  }
];

// Seed database
async function seedDatabase() {
  try {
    // Connect to MongoDB
    console.log('Connecting to database...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing books
    await Book.deleteMany({});
    console.log('Cleared existing books');

    // Insert new books
    const insertedBooks = await Book.insertMany(books);
    console.log(`Successfully seeded ${insertedBooks.length} books into MongoDB.`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
